Poprawilam selektory , ale niestety dalej pobiera jeden dom . tyle ze…
anetapec/scrapy pull request #4
Opened 2023-02-11 21:25 UTC by anetapec

Poprawilam selektory , ale niestety dalej pobiera jeden dom . ..tyle ze juz nie w nieskonczonosc....

2023-02-13 22:17 UTC, bagaw1 requested changes

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
>      start_urls = ['https://ogloszenia.trojmiasto.pl/nieruchomosci/dom/gdynia/']
W tym folderze jest z duplikowany plik tricity\requiments.txt. Ten plik powinien być tylko w głównym foldrze. Ten z tego folderu trzeba usunąć.

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/tricity.csv
> +area,number_of_rooms,price,price_per_meter,url
Ten plik trzeba usunąć. z gita. Usuń ten plik i dodaj tą zmianę usunięcia pliku do gita. Dodaj do pliku .gitignore w głównym folderze "*.csv" tak żeby git ignorował tego typy pliki w przyszłości.

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity2.csv
> +area,number_of_rooms,price,price_per_meter,url
Ten plik też trzeba usunąć z git a. Nie będziemy trzymać plików csv w git.

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
Dodaj do pliku README.md w folderze głównym w jaki sposób odpalać tego spidera

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
>          for house in houses:
Zmień wszystkie XPATHy na CSSSelectors. Od teraz będziemy używać tylko i wyłącznie CSSSelectors

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
>          for house in houses:
`house`  jest instancją obiektu która pobierasz do pętli `for`. Nie jest ani razu użyta. Dlatego też cały czas pobierasz dane z jednego elementu.

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
> +            house_item['price'] = response.css('p.list__item__price__value::text').get().replace('zł', '')
tutaj trzeba odnieść się do elementu który pobierasz do pętli 'for' czyli `house`,  więc targetowanie poprzez CSS powinno być 
house.css('p.list__item__price__value::text').get().replace('zł', '').
Nie wiem czy jak zmienisz element z `response` na `house` to twoj selector css dalej będzie działać. Możesz popróbować za pomocą albo Debugger'a w VSCode albo za pomocą `scrapy shell`.  Debugowanie to jest narzędzie którym posługujemy się gdy coś nie działa i nie wiemy czemu. Wtedy można sprawdzić linijkę po linijce podczas odpalania kodu.
https://docs.scrapy.org/en/latest/topics/shell.html

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
> +            house_item['price'] = response.css('p.list__item__price__value::text').get().replace('zł', '')
Żeby dostać wszystkie wyświetlane domy możesz np. użyć selectora css `'#ogl__list__wrap .list__item'`

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
> +            house_item['area'] = response.xpath("//p[@class='list__item__details__icons__element__desc']//text()").get().replace('\n                                            ', '').replace('\n
Jak chcesz usunąć białe znaki to trzeba je namierzyć za pomocą wyrażenia regularnego a dosłownej ilości białych znaków.
Tutaj link to poczytania i poćwiczenia.
https://regexone.com/lesson/whitespaces

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
> +            house_item['number_of_rooms'] = response.xpath('//ul/li[2]/div/p[2]//text()').get().replace('\n                                            ', '').replace('\n
Tutaj też regex na usunięcie buałych znaków i zastąp XPatha za pomocą selectora CSS

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
> +        next_page = response.css('span.pages__item__active').get()
Do przełączania się na nową stronę to musisz pobrać wartość atrybutu HREF z elementu HTML <a href=">.  Tym elementem na stronie jest `>` przełącza na kolejną stronę. Tutaj jak to można zrobić z przykładem
https://stackoverflow.com/questions/21181628/get-href-using-css-selector-with-scrapy.

Jak będziesz miała tą wartość to będzie coś jak "?strona=1", to wtedy musisz to połączyć z URL strony, można to pobrać albo z array  start_urls (linijka nr. 7 ) który jest property klasy HousesspiderSpider, albo w debuggerze można sprawdzić czy obiekt `response` nie ma jakiejś informacji którą można użyć.

2023-02-13 22:17 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
> +            yield response.follow(next_page, callback=self.parse)
Ostateczenie zmienna `next_page` , którą przekazujesz do metody `.follow()` to musi być pełen link kolejnej strony np. `https://ogloszenia.trojmiasto.pl/nieruchomosci/dom/gdynia/?strona=1` , gdzie numer strony będzie się zmieniał w zależności od strony, ale ta informacja będzie pobierana z elementu HTML <a> z jego atrybutu HTLM, tak jak w komentarzu powyżej.

2023-02-15 11:05 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
Przykładowa zawartość pliku README.md
# hip-performance-tests


Create virtual environment
```bash
cd .
python -m venv .venv
```

Activate VENV
```bash
.\.venv\Scripts\Activate.ps1
```

Install from requirements
```bash
pip install -r requirements.txt
```

### Running headless instance
```bash
locust -f .\sc1-ext.py --headless --users 10 --spawn-rate 1  -H https://ppe.westeurope.api.hip.inter.ikea.net
```


```bash
locust -f .\sc1-ext.py --users 10 --spawn-rate 1 -H https://ppe.westeurope.api.hip.inter.ikea.net

```

2023-02-17 10:21 UTC, anetapec commented on tricity/tricity/spiders/trojmiasto.py
>      start_urls = ['https://ogloszenia.trojmiasto.pl/nieruchomosci/dom/gdynia/']
usuniete

2023-02-20 13:43 UTC, anetapec commented
Jak ominąć problem gdy program się wysypuje podczas natrafienia ogłoszenia bez danych które ściągamy

2023-02-21 09:48 UTC, anetapec reviewed
próba przywrócenia

2023-02-21 20:18 UTC, anetapec commented
czy to o to chodzi z tym ID ? program nie działa ..ale powiedz czy to miałeś na mysli ....

2023-02-22 13:08 UTC, bagaw1 approved these changes

2023-02-22 13:08 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
> +                #house_item['price_per_meter'] = float(round((house_item['price']) / float(house_item['area'])), 2)
To będziemy wyliczać w Pipelines (dalszym procesowaniu danych). A nie w tym miejscu.

2023-02-22 13:08 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
> +        for house_item in HouseItem():
To też będziemy wyliczać w Pipelines (dalszym procesowaniu danych). Nie w momencie pobierania danych.
https://docs.scrapy.org/en/latest/topics/item-pipeline.html. Usuń narazie ten kawałek kodu z tego brancha. Stwórz sobie inny branch. Tego będziemy mergować.

2023-02-22 13:08 UTC, bagaw1 commented on tricity/tricity/spiders/trojmiasto.py
> +            except:
Tak o to chodziło. To jest jeden ze sposobów jak można to rozwiązać.

2023-02-22 21:28 UTC, anetapec reviewed
ostateczny etap pobierania danych ze strony .

2023-02-22 21:29 UTC, anetapec commented
etap pierwszy

2023-02-22 22:09 UTC, anetapec commented
.

2023-03-23 08:48 UTC, closed without merging