Feature/plotly
anetapec/scrapy pull request #9
Opened 2023-04-04 23:19 UTC by anetapec

stanęłam na tym musze sie zapoznać z tym plotly , ale czy dobrze rozumiem?- kolejny krok to utworzenie tabel na podstawie tych wyliczonych wartosci i przedziału czasowego a później utworzenie wykresów ?

2023-04-05 10:25 UTC, bagaw1 requested changes

2023-04-05 10:25 UTC, bagaw1 commented on dashboards/app.py
> +    avg_by_price = data_source.df.groupby('scrapping_date')['price'].mean()
To grupuje po konkretnej dacie scrappowania, co jeżeli dane scrapowane byłyby 2 razy tego samego dnia?

2023-04-05 10:25 UTC, bagaw1 commented on dashboards/app.py
> +    avg_by_price = data_source.df.groupby('scrapping_date')['price'].mean()
Musisz pogrupować po całym dniu a nie po konkretnym timestampie

2023-04-05 10:25 UTC, bagaw1 commented on dashboards/app.py
> +    number_houses_exposed = data_source.df.value_counts('last_seen_date')['2023-04-04 21:53:02']
Ta linijka rzuca wyjątek, nie możemy urzyć dokładnej daty (timestampa) '2023-04-04 21:53:02' musimy pogrupować po całych dniach

2023-04-05 10:25 UTC, bagaw1 commented on dashboards/app.py
> +    data_source.df['last_seen_date'] = data_source.df['last_seen_date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))
Nie modyfikujmy pierwotnej wartości last_seen_date a stwórzmy nową kolumnę o innej bardziej pasującej nazwie

2023-04-05 10:25 UTC, bagaw1 commented on dashboards/app.py
> +    number_houses_exposed = data_source.df.value_counts('last_seen_date')['2023-04-04 21:53:02']
Nazwa zmiennej `number_houses_exposed` nie jest odpowiednia nie mówi o co dokładnie chodzi powinna być inna np `houses_sold_on_date` - ta nazwa zmiennej mówi o jest bardziej informatywna

2023-04-05 10:25 UTC, bagaw1 commented on dashboards/app.py
> +    houses_sold_in_a_period_of_time = data_source.df.sort_index().loc['2023-04-02':'2023-04-03']
Nie możemy użyć loc[] bo nie jest to elastyczne. Chciałbym żeby domyślnie pokazywało wszystkie dane za 1 miesiąc wstecz. Nie za cały misiąć ale od konkretnej daty.

2023-04-05 10:25 UTC, bagaw1 commented on dashboards/app.py
> +    data_source.df['last_seen_date'] = data_source.df['last_seen_date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))
Lepiej daty które są stringami zmienić w pandas DataFrame na typ DateTime wtedy będziesz mogła robić na tych danych odpowiednie operacje bez modyfikacji danych >
https://stackoverflow.com/questions/24082784/pandas-dataframe-groupby-datetime-month

2023-04-05 10:25 UTC, bagaw1 commented on dashboards/app.py
> +    data_source.df['last_seen_date'] = data_source.df['last_seen_date'].apply(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))
![image](https://user-images.githubusercontent.com/115139906/230053879-e2c296c4-a7da-4bcf-a5b8-a2ee51a8d476.png)

2023-04-05 18:13 UTC, anetapec commented on dashboards/app.py
> +    number_houses_exposed = data_source.df.value_counts('last_seen_date')['2023-04-04 21:53:02']
zmieniam na number_of_houses_for_sale bo tu wyliczam ile jest domów wystawonych na sprzedaż

2023-04-09 00:07 UTC, anetapec commented
niestety nie moge tego sprawdzić bo jak wchodzę w http://127.0.0.1:8050/ w przegladarce mam problemy z proxy , a nie mam siły juz sie z tym meczyc ....ale jesli to ma byc cos na ten styl to sprawdze czy dziala i najwyzej uzupelnie kod

2023-05-07 21:12 UTC, anetapec commented
Niestety nie udało mi sie pominąć kolumny pierwszego scrapowania. bede jeszcze przegladać materiały moze jeszcze cos wymyślę , i chciałam te przerwy jakoś w wykresach liniowych zrobić by nie było takich dziur ....,

2023-05-19 07:38 UTC, closed without merging